apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-resources-quota-sushi
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policies-test-resources-quota
        spec:
          remediationAction: inform
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - test-policies
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: resource-quotas
                spec:
                  hard:
                    limits.cpu: '2'
                    limits.memory: 2Gi
                    pods: '4'
                    requests.cpu: '1'
                    requests.memory: 2Gi
                    requests.storage: 3Gi
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-resources-quota-sushi
  namespace: rhacm-policies
placementRef:
  name: placement-policy-resources-quota-sushi
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-resources-quota-sushi
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-resources-quota-sushi
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: arch
        operator: In
        values:
          - s390x
          - ppc64le
          - x86
