apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-role-mariadb-viewer
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-role-mariadb-viewer
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          namespaceSelector:
            include: ["mariadb"]
          object-templates:
            - complianceType: mustonlyhave # role definition should exact match
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: dc-viewer-role
                rules:
                  - apiGroups: ["apps.openshift.io", ""]
                    resources: ["deploymentconfigs"]
                    verbs: ["get", "list", "watch", "patch", "update"]
                  - apiGroups: [""]
                    resources: ["replicationcontrollers"]
                    verbs: ["update", "patch", "list", "get"]
                  - apiGroups: [""]
                    resources: ["pods"]
                    verbs: ["get", "list", "watch"]
