apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-limitrange-sushi
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: test-policies-limit-range-container-limit-range
        spec:
          remediationAction: inform
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - test-policies
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name: container-limit-range
                spec:
                  limits:
                    - default:
                        cpu: 500m
                        memory: 512Mi
                      defaultRequest:
                        cpu: 50m
                        memory: 256Mi
                      type: Container
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-limitrange-sushi
  namespace: rhacm-policies
placementRef:
  name: placement-policy-limitrange-sushi
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-limitrange-sushi
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-limitrange-sushi
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: arch
        operator: In
        values:
          - s390x
          - x86
          - ppc64le
