---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-certificate
  namespace: rhacm-policies
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: CertificatePolicy
        metadata:
          name: policy-certificate-example
        spec:
          namespaceSelector:
            include:
            - openshift-ingress
            exclude: []
          remediationAction: inform
          severity: low
          minimumDuration: 2200h
